### ISSUE TITLE
Enhancement: additional percentage digits

### ISSUE THREAD

**Issue by rilitili** [HH-GAME-MM/HH-Simulate-Headband-in-Pantheon#1]
Hi MM, could you add some additional digits to the % simulator?
0% isn't very useful for determining which gear one should wear.
0,0001% would be more useful and practical.

**Comment by HH-GAME-MM** [comment]
Hi rilitili

You can see more digits in the browser console (open it with the F12 key). To do this, you need to enable the setting "Detailed logging in the browser console" in HH++. I have attached screenshots for you.

I hope I was able to help you.

Best regards
-MM-

**Settings:**
![settings](https://user-images.githubusercontent.com/107755486/217491185-ae58692b-78da-48d4-8b1b-fba481264251.png)

**Console output:**
![console](https://user-images.githubusercontent.com/107755486/217491244-117ed15e-0af7-4b79-b910-6bfbeab42a4c.PNG)

**Comment by rilitili** [comment]
Thanks bro.
